name: CI

on: ["pull_request"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install pipenv
        run: |
          python -mpip install pipenv

      - name: Install dependencies
        run: |
          make install-dependencies  # Install dependencies in pipenv virtual env

      - name: Run tests
        run: |
          pipenv run make test
